module.exports={
  entry:'./src/app.js',
  output:{
    filename:'./public/bundle.js'
  },
  module:{
    loaders:[
      {
        test:/\.js$/,
        loader:'babel-loader',
        exclude:/node_modules/,
        query:{
          presets:['es2015','react','stage-0']
        }
      }
    ]
  }
}